version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy

jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin https://registry.alexhicks.net
            docker build -t "$DOCKER_REPO:latest" .
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Deploy Docker image
                command: docker push "$DOCKER_REPO:latest"
