version: 2.1

workflows:
  build_and_publish:
    jobs:
      - build_and_publish:
          context: ah-global

jobs:
  build_and_publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate Docker
          command: |
            echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
      - run:
          name: Build Docker image
          command: |
            docker build -t "$DOCKER_REPO:latest" .
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Push Docker image
                command: |
                  docker push "$DOCKER_REPO:latest"
